import type { NextPage } from 'next';
import Head from 'next/head';

const A: NextPage = () => {
  return (
    <div>
      <Head>
        <title>A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      A
    </div>
  )
}

export default A
