import { useEffect, useState, useReducer } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Swiper, SwiperSlide } from "swiper/react";
import { Mousewheel, EffectFade } from "swiper";
import Siders from './home/Siders';


import "swiper/css";
import "swiper/css/effect-fade";

import styles from '../styles/Home.module.css';

const Main: NextPage = () => {
  const [swiperDom,setSwiperDom] = useState<any>({});
  const [selectTag, setSelectTag] = useState<number>(0)
  
  const navs = [
    {
      name:  "news",
      href:"/news"
    },
    {
      name:  "Project",
      href:"/Project"
    },
  ]


  useEffect(() => {
    // const swiper = new Swiper();
      console.log("swiper", swiperDom)
      console.log("selectTag", selectTag)
    if(swiperDom.slideTo) {
      console.log("swiper", swiperDom.slideTo)
      swiperDom.slideTo(selectTag)
    }
  },[selectTag])

  const onChangeSider:<T>(val:T, index: number) => void = (val, index) => {
    setSelectTag(index)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* 侧边栏 */}
        <Siders
          list={navs}
          selected={selectTag}
          onChange={onChangeSider} />
        {/* 主内容 */}
        <Swiper
          slidesPerView="auto"
          direction="vertical"
          effect={"fade"}
          className={styles.swiperbox}
          mousewheel={true}
          allowTouchMove={false}
          onSlideChange={() => console.log("slide change")}
          onSwiper={(swiper) => { setSwiperDom(swiper) }}
          modules={[Mousewheel, EffectFade]}
        >
          
          <SwiperSlide className={styles.slider}>
            <Image layout="fill" src="https://swiperjs.com/demos/images/nature-1.jpg" alt="" />
          </SwiperSlide>
          <SwiperSlide className={styles.slider}>
            <Image layout="fill" src="https://swiperjs.com/demos/images/nature-2.jpg" alt="" />
          </SwiperSlide>
          <SwiperSlide className={styles.slider}>
            <Image layout="fill" src="https://swiperjs.com/demos/images/nature-3.jpg" alt="" />
          </SwiperSlide>
          <SwiperSlide className={styles.slider}>
            <Image layout="fill" src="https://swiperjs.com/demos/images/nature-4.jpg" alt="" />
          </SwiperSlide>
          {/* <SwiperSlide className={styles.slider}>Slide 133</SwiperSlide>
          <SwiperSlide className={styles.slider}>Slide 2</SwiperSlide>
          <SwiperSlide className={styles.slider}>Slide 3</SwiperSlide>
          <SwiperSlide className={styles.slider}>Slide 4</SwiperSlide> */}
        </Swiper>
      </main>
    </div>
  )
}

export default Main
