import type { NextPage } from 'next';
import Head from 'next/head';

const B: NextPage = () => {
  return (
    <div>
      <Head>
        <title>B</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      B
    </div>
  )
}

export default B;
